name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: install require dependency and publish to GitHub pages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: |
          npm ci
          cp ./node_modules/mathjs/lib/browser/math.js ./scripts/math.js 
          rm -r ./node_modules

      - name: Check if branch exists
        run: |
          if git show-ref --quiet refs/heads/gh-pages; then
            git checkout gh-pages
          else
            echo "The 'gh-pages' branch doesn't exist. Creating it..."
            git checkout -b gh-pages
          fi

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "51868695+AlstonChan@users.noreply.github.com"
          git add .
          git commit -m "Deploy site"
          git push origin gh-pages
